In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [19]:
df = pd.read_csv('Energy_and_Water_Data_Disclosure_for_Local_Law_84_2017__Data_for_Calendar_Year_2016_.csv')
df.head()

,Order,Property Id,Property Name,Parent Property Id,Parent Property Name,BBL - 10 digits,"NYC Borough, Block and Lot (BBL) self-reported",NYC Building Identification Number (BIN),Address 1 (self-reported),Address 2,...,Source EUI (kBtu/ft²),Release Date,Water Required?,DOF Benchmarking Submission Status,Latitude,Longitude,Community Board,Council District,Census Tract,NTA
0,1,13286,201/205,13286,201/205,1013160001,1013160001,1037549,201/205 East 42nd st.,Not Available,...,619.4,05/01/2017 05:32:03 PM,No,In Compliance,40.750791,-73.973963,6.0,4.0,88.0,Turtle Bay-East Midtown ...
1,2,28400,NYP Columbia (West Campus),28400,NYP Columbia (West Campus),1021380040,1-02138-0040,1084198; 1084387;1084385; 1084386; 1084388; 10...,622 168th Street,Not Available,...,404.3,04/27/2017 11:23:27 AM,No,In Compliance,40.841402,-73.942568,12.0,10.0,251.0,Washington Heights South ...
2,3,4778226,MSCHoNY North,28400,NYP Columbia (West Campus),1021380030,1-02138-0030,1063380,3975 Broadway,Not Available,...,Not Available,04/27/2017 11:23:27 AM,No,In Compliance,40.840427,-73.940249,12.0,10.0,251.0,Washington Heights South ...
3,4,4778267,Herbert Irving Pavilion & Millstein Hospital,28400,NYP Columbia (West Campus),1021390001,1-02139-0001,1087281; 1076746,161 Fort Washington Ave,177 Fort Washington Ave,...,Not Available,04/27/2017 11:23:27 AM,No,In Compliance,40.840746,-73.942854,12.0,10.0,255.0,Washington Heights South ...
4,5,4778288,Neuro Institute,28400,NYP Columbia (West Campus),1021390085,1-02139-0085,1063403,710 West 168th Street,Not Available,...,Not Available,04/27/2017 11:23:27 AM,No,In Compliance,40.841559,-73.942528,12.0,10.0,255.0,Washington Heights South ...

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11435 entries, 0 to 11434
Data columns (total 60 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Order                                                       11435 non-null  int64
 1   Property Id                                                 11435 non-null  int64
 2   Property Name                                               11435 non-null  object
 3   Parent Property Id                                          11435 non-null  object
 4   Parent Property Name                                        11434 non-null  object
 5   BBL - 10 digits                                             11423 non-null  object
 6   NYC Borough, Block and Lot (BBL) self-reported              11434 non-null  object
 7   NYC Building Identification Number (BIN)                    11434 non-null  object
 8   Address 1 (self-reported)                                   11434 non-null  object
 9   Address 2                                                   11434 non-null  object
 10  Postal Code                                                 11434 non-null  object
 11  Street Number                                               11314 non-null  object
 12  Street Name                                                 11316 non-null  object
 13  Borough                                                     11320 non-null  object
 14  DOF Gross Floor Area                                        11320 non-null  float64
 15  Primary Property Type - Self Selected                       11434 non-null  object
 16  List of All Property Use Types at Property                  11434 non-null  object
 17  Largest Property Use Type                                   11434 non-null  object
 18  Largest Property Use Type - Gross Floor Area (ft²)          11434 non-null  object
 19  2nd Largest Property Use Type                               11434 non-null  object
 20  2nd Largest Property Use - Gross Floor Area (ft²)           11434 non-null  object
 21  3rd Largest Property Use Type                               11434 non-null  object
 22  3rd Largest Property Use Type - Gross Floor Area (ft²)      11434 non-null  object
 23  Year Built                                                  11434 non-null  float64
 24  Number of Buildings - Self-reported                         11434 non-null  float64
 25  Occupancy                                                   11434 non-null  float64
 26  Metered Areas (Energy)                                      11434 non-null  object
 27  Metered Areas  (Water)                                      11434 non-null  object
 28  ENERGY STAR Score                                           11434 non-null  object
 29  Site EUI (kBtu/ft²)                                         11434 non-null  object
 30  Weather Normalized Site EUI (kBtu/ft²)                      11434 non-null  object
 31  Weather Normalized Site Electricity Intensity (kWh/ft²)     11434 non-null  object
 32  Weather Normalized Site Natural Gas Intensity (therms/ft²)  11434 non-null  object
 33  Weather Normalized Source EUI (kBtu/ft²)                    11434 non-null  object
 34  Fuel Oil #1 Use (kBtu)                                      11434 non-null  object
 35  Fuel Oil #2 Use (kBtu)                                      11434 non-null  object
 36  Fuel Oil #4 Use (kBtu)                                      11434 non-null  object
 37  Fuel Oil #5 & 6 Use (kBtu)                                  11434 non-null  object
 38  Diesel #2 Use (kBtu)                                        11434 non-null  object
 39  District Steam Use (kBtu)                                   11434 non-null  object
 40  Natural Gas Use (kBtu)                                      11434 non-null  object
 41  Weather Normalized Site Natural Gas Use (therms)            11434 non-null  object
 42  Electricity Use - Grid Purchase (kBtu)                      11434 non-null  object
 43  Weather Normalized Site Electricity (kWh)                   11434 non-null  object
 44  Total GHG Emissions (Metric Tons CO2e)                      11434 non-null  object
 45  Direct GHG Emissions (Metric Tons CO2e)                     11434 non-null  object
 46  Indirect GHG Emissions (Metric Tons CO2e)                   11434 non-null  object
 47  Property GFA - Self-Reported (ft²)                          11434 non-null  float64
 48  Water Use (All Water Sources) (kgal)                        11434 non-null  object
 49  Water Intensity (All Water Sources) (gal/ft²)               11434 non-null  object
 50  Source EUI (kBtu/ft²)                                       11434 non-null  object
 51  Release Date                                                11434 non-null  object
 52  Water Required?                                             11328 non-null  object
 53  DOF Benchmarking Submission Status                          11434 non-null  object
 54  Latitude                                                    9306 non-null   float64
 55  Longitude                                                   9306 non-null   float64
 56  Community Board                                             9306 non-null   float64
 57  Council District                                            9306 non-null   float64
 58  Census Tract                                                9306 non-null   float64
 59  NTA                                                         9306 non-null   object
dtypes: float64(10), int64(2), object(48)
memory usage: 5.2+ MB

In [21]:
for col in df.columns:
    df = df[df[col].notna()]
print(df[df.columns[0]].size)
df.info()

9232
<class 'pandas.core.frame.DataFrame'>
Int64Index: 9232 entries, 0 to 10792
Data columns (total 60 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Order                                                       9232 non-null   int64
 1   Property Id                                                 9232 non-null   int64
 2   Property Name                                               9232 non-null   object
 3   Parent Property Id                                          9232 non-null   object
 4   Parent Property Name                                        9232 non-null   object
 5   BBL - 10 digits                                             9232 non-null   object
 6   NYC Borough, Block and Lot (BBL) self-reported              9232 non-null   object
 7   NYC Building Identification Number (BIN)                    9232 non-null   object
 8   Address 1 (self-reported)                                   9232 non-null   object
 9   Address 2                                                   9232 non-null   object
 10  Postal Code                                                 9232 non-null   object
 11  Street Number                                               9232 non-null   object
 12  Street Name                                                 9232 non-null   object
 13  Borough                                                     9232 non-null   object
 14  DOF Gross Floor Area                                        9232 non-null   float64
 15  Primary Property Type - Self Selected                       9232 non-null   object
 16  List of All Property Use Types at Property                  9232 non-null   object
 17  Largest Property Use Type                                   9232 non-null   object
 18  Largest Property Use Type - Gross Floor Area (ft²)          9232 non-null   object
 19  2nd Largest Property Use Type                               9232 non-null   object
 20  2nd Largest Property Use - Gross Floor Area (ft²)           9232 non-null   object
 21  3rd Largest Property Use Type                               9232 non-null   object
 22  3rd Largest Property Use Type - Gross Floor Area (ft²)      9232 non-null   object
 23  Year Built                                                  9232 non-null   float64
 24  Number of Buildings - Self-reported                         9232 non-null   float64
 25  Occupancy                                                   9232 non-null   float64
 26  Metered Areas (Energy)                                      9232 non-null   object
 27  Metered Areas  (Water)                                      9232 non-null   object
 28  ENERGY STAR Score                                           9232 non-null   object
 29  Site EUI (kBtu/ft²)                                         9232 non-null   object
 30  Weather Normalized Site EUI (kBtu/ft²)                      9232 non-null   object
 31  Weather Normalized Site Electricity Intensity (kWh/ft²)     9232 non-null   object
 32  Weather Normalized Site Natural Gas Intensity (therms/ft²)  9232 non-null   object
 33  Weather Normalized Source EUI (kBtu/ft²)                    9232 non-null   object
 34  Fuel Oil #1 Use (kBtu)                                      9232 non-null   object
 35  Fuel Oil #2 Use (kBtu)                                      9232 non-null   object
 36  Fuel Oil #4 Use (kBtu)                                      9232 non-null   object
 37  Fuel Oil #5 & 6 Use (kBtu)                                  9232 non-null   object
 38  Diesel #2 Use (kBtu)                                        9232 non-null   object
 39  District Steam Use (kBtu)                                   9232 non-null   object
 40  Natural Gas Use (kBtu)                                      9232 non-null   object
 41  Weather Normalized Site Natural Gas Use (therms)            9232 non-null   object
 42  Electricity Use - Grid Purchase (kBtu)                      9232 non-null   object
 43  Weather Normalized Site Electricity (kWh)                   9232 non-null   object
 44  Total GHG Emissions (Metric Tons CO2e)                      9232 non-null   object
 45  Direct GHG Emissions (Metric Tons CO2e)                     9232 non-null   object
 46  Indirect GHG Emissions (Metric Tons CO2e)                   9232 non-null   object
 47  Property GFA - Self-Reported (ft²)                          9232 non-null   float64
 48  Water Use (All Water Sources) (kgal)                        9232 non-null   object
 49  Water Intensity (All Water Sources) (gal/ft²)               9232 non-null   object
 50  Source EUI (kBtu/ft²)                                       9232 non-null   object
 51  Release Date                                                9232 non-null   object
 52  Water Required?                                             9232 non-null   object
 53  DOF Benchmarking Submission Status                          9232 non-null   object
 54  Latitude                                                    9232 non-null   float64
 55  Longitude                                                   9232 non-null   float64
 56  Community Board                                             9232 non-null   float64
 57  Council District                                            9232 non-null   float64
 58  Census Tract                                                9232 non-null   float64
 59  NTA                                                         9232 non-null   object
dtypes: float64(10), int64(2), object(48)
memory usage: 4.3+ MB

In [22]:
len(df.columns)

60

In [23]:
df.drop_duplicates(inplace=True)
df[df.columns[0]].size

9232

In [24]:
for i in range(df.columns.size):
    if df.dtypes[i] == object:
        df[df.columns[i]] = df[df.columns[i]].astype(str)
df.dtypes

Order                                                           int64
Property Id                                                     int64
Property Name                                                  object
Parent Property Id                                             object
Parent Property Name                                           object
BBL - 10 digits                                                object
NYC Borough, Block and Lot (BBL) self-reported                 object
NYC Building Identification Number (BIN)                       object
Address 1 (self-reported)                                      object
Address 2                                                      object
Postal Code                                                    object
Street Number                                                  object
Street Name                                                    object
Borough                                                        object
DOF Gross Floor Area                                          float64
Primary Property Type - Self Selected                          object
List of All Property Use Types at Property                     object
Largest Property Use Type                                      object
Largest Property Use Type - Gross Floor Area (ft²)             object
2nd Largest Property Use Type                                  object
2nd Largest Property Use - Gross Floor Area (ft²)              object
3rd Largest Property Use Type                                  object
3rd Largest Property Use Type - Gross Floor Area (ft²)         object
Year Built                                                    float64
Number of Buildings - Self-reported                           float64
Occupancy                                                     float64
Metered Areas (Energy)                                         object
Metered Areas  (Water)                                         object
ENERGY STAR Score                                              object
Site EUI (kBtu/ft²)                                            object
Weather Normalized Site EUI (kBtu/ft²)                         object
Weather Normalized Site Electricity Intensity (kWh/ft²)        object
Weather Normalized Site Natural Gas Intensity (therms/ft²)     object
Weather Normalized Source EUI (kBtu/ft²)                       object
Fuel Oil #1 Use (kBtu)                                         object
Fuel Oil #2 Use (kBtu)                                         object
Fuel Oil #4 Use (kBtu)                                         object
Fuel Oil #5 & 6 Use (kBtu)                                     object
Diesel #2 Use (kBtu)                                           object
District Steam Use (kBtu)                                      object
Natural Gas Use (kBtu)                                         object
Weather Normalized Site Natural Gas Use (therms)               object
Electricity Use - Grid Purchase (kBtu)                         object
Weather Normalized Site Electricity (kWh)                      object
Total GHG Emissions (Metric Tons CO2e)                         object
Direct GHG Emissions (Metric Tons CO2e)                        object
Indirect GHG Emissions (Metric Tons CO2e)                      object
Property GFA - Self-Reported (ft²)                            float64
Water Use (All Water Sources) (kgal)                           object
Water Intensity (All Water Sources) (gal/ft²)                  object
Source EUI (kBtu/ft²)                                          object
Release Date                                                   object
Water Required?                                                object
DOF Benchmarking Submission Status                             object
Latitude                                                      float64
Longitude                                                     float64
Community Board                                               float64
Council District                                              float64
Census Tract                                                  float64
NTA                                                            object
dtype: object

In [25]:
#spl 80-20
train, test = train_test_split(df, test_size=0.2)

In [44]:
x_train = train['Source EUI (kBtu/ft²)']
y_train = train['Water Use (All Water Sources) (kgal)']
x_train = pd.to_numeric(x_train, errors='coerce')
y_train = pd.to_numeric(y_train, errors='coerce')

In [47]:
modelLR = LinearRegression()
#modelLR.fit()

pandas.core.series.Series